export const ADMIN_ROUTE = '/admin'
export const AUTH_ROUTE = '/auth'
export const MODELS_ROUTE = '/models'
export const HOME_ROUTE = '/'
export const REACT_APP_API_URL = 'https://lemar-models.ru:5000/'
export const M_NUMBER = '79106771060'
